"""initial schema

Revision ID: 825bb97ca967
Revises: 
Create Date: 2026-05-08 18:07:29.262905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '825bb97ca967'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension up front (used by sub-project #6).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository',
    sa.Column('github_id', sa.Text(), nullable=False),
    sa.Column('owner_handle', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('star_count_observed', sa.Integer(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('github_id')
    )
    op.create_index(op.f('ix_repository_full_name'), 'repository', ['full_name'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_table('human_review_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('pending','resolved','dismissed')", name='ck_hrq_status'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('investor_type', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('sector_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('stage_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('role_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_entity_type'), 'person', ['entity_type'], unique=False)
    op.create_index(op.f('ix_person_org_id'), 'person', ['org_id'], unique=False)
    op.create_table('scraper_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('used_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.Text(), server_default='healthy', nullable=False),
    sa.Column('ban_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health IN ('healthy','cooldown','banned')", name='ck_sa_health'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rule',
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('convergence_event',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('target_person_id', sa.UUID(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distinct_member_count', sa.Integer(), nullable=False),
    sa.Column('member_person_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_type_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ce_org_score', 'convergence_event', ['org_id', 'score'], unique=False)
    op.create_index(op.f('ix_convergence_event_target_person_id'), 'convergence_event', ['target_person_id'], unique=False)
    op.create_table('edge_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('watcher_person_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.Text(), nullable=False),
    sa.Column('target_person_id', sa.UUID(), nullable=True),
    sa.Column('target_repo_id', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('edge_confidence', sa.Float(), nullable=True),
    sa.Column('raw_artifact_ref', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(target_kind = 'person'     AND target_person_id IS NOT NULL AND target_repo_id IS NULL) OR (target_kind = 'repository' AND target_repo_id   IS NOT NULL AND target_person_id IS NULL)", name='ck_ee_target_oneof'),
    sa.CheckConstraint("source IN ('github','twitter','linkedin')", name='ck_ee_source'),
    sa.CheckConstraint("target_kind IN ('person','repository')", name='ck_ee_target_kind'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['target_repo_id'], ['repository.github_id'], ),
    sa.ForeignKeyConstraint(['watcher_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ee_org_source_observed', 'edge_event', ['org_id', 'source', 'observed_at'], unique=False)
    op.create_index('idx_ee_target_person_observed', 'edge_event', ['target_person_id', 'observed_at'], unique=False, postgresql_where="target_kind = 'person'")
    op.create_index('idx_ee_target_repo_observed', 'edge_event', ['target_repo_id', 'observed_at'], unique=False, postgresql_where="target_kind = 'repository'")
    op.create_index('idx_ee_watcher_observed', 'edge_event', ['watcher_person_id', 'observed_at'], unique=False)
    op.create_table('feedback_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('convergence_event','dossier')", name='ck_fe_target_type'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fe_target', 'feedback_event', ['target_type', 'target_id'], unique=False)
    op.create_table('identity_decision',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.CheckConstraint("decision_type IN ('merge','distinct','override')", name='ck_id_type'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_identity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('handle_original', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('verified_via', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("platform IN ('github','twitter','linkedin')", name='ck_pi_platform'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_pi_platform_handle')
    )
    op.create_index(op.f('ix_platform_identity_person_id'), 'platform_identity', ['person_id'], unique=False)
    op.create_table('repository_owner',
    sa.Column('repo_id', sa.Text(), nullable=False),
    sa.Column('owner_person_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.github_id'], ),
    sa.PrimaryKeyConstraint('repo_id', 'owner_person_id')
    )
    op.create_table('watchlist_member',
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('archetype', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IN ('active','vip','reference')", name='ck_wm_tier'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'user_id', 'person_id')
    )
    op.create_index('idx_wm_user_tier', 'watchlist_member', ['user_id', 'tier'], unique=False)
    op.create_table('dossier_classification',
    sa.Column('convergence_event_id', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convergence_event_id'], ['convergence_event.id'], ),
    sa.PrimaryKeyConstraint('convergence_event_id')
    )
    # ### end Alembic commands ###

    # Partial unique index for edge_event dedup (COALESCE expression cannot be
    # expressed via SQLAlchemy Index alone). The ON CONFLICT clause in
    # scrapers/persistence.record_edge_event references this exact expression.
    op.execute(
        "CREATE UNIQUE INDEX uq_ee_observation_dedup ON edge_event "
        "(source, action_type, watcher_person_id, "
        " COALESCE(target_person_id::text, target_repo_id))"
    )

    # Bootstrap rows so org_id='demo' / user_id='demo' work without auth (#7).
    op.execute("INSERT INTO org (id, name) VALUES ('demo', 'Demo Org')")
    op.execute("INSERT INTO app_user (id, org_id) VALUES ('demo', 'demo')")


def downgrade() -> None:
    # Clean any data dependent on the demo bootstrap rows before deleting them.
    # The 'demo' org/user bootstraps participate in many FK chains; we drop
    # orphaned children first so the bootstrap delete doesn't FK-error.
    op.execute("DELETE FROM alert_rule           WHERE org_id = 'demo'")
    op.execute("DELETE FROM feedback_event       WHERE org_id = 'demo'")
    op.execute("DELETE FROM identity_decision    WHERE person_id IN (SELECT id FROM person WHERE org_id = 'demo')")
    op.execute("DELETE FROM dossier_classification WHERE convergence_event_id IN (SELECT id FROM convergence_event WHERE org_id = 'demo')")
    op.execute("DELETE FROM convergence_event    WHERE org_id = 'demo'")
    op.execute("DELETE FROM edge_event           WHERE org_id = 'demo'")
    op.execute("DELETE FROM watchlist_member     WHERE org_id = 'demo'")
    op.execute("DELETE FROM repository_owner     WHERE owner_person_id IN (SELECT id FROM person WHERE org_id = 'demo')")
    op.execute("DELETE FROM platform_identity    WHERE person_id IN (SELECT id FROM person WHERE org_id = 'demo')")
    op.execute("DELETE FROM person               WHERE org_id = 'demo'")
    op.execute("DELETE FROM scraper_account      WHERE org_id = 'demo'")
    op.execute("DELETE FROM human_review_queue   WHERE org_id = 'demo'")
    op.execute("DELETE FROM app_user             WHERE id = 'demo'")
    op.execute("DELETE FROM org                  WHERE id = 'demo'")
    op.execute("DROP INDEX IF EXISTS uq_ee_observation_dedup")
    # vector extension intentionally not dropped — other DBs may rely on it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dossier_classification')
    op.drop_index('idx_wm_user_tier', table_name='watchlist_member')
    op.drop_table('watchlist_member')
    op.drop_table('repository_owner')
    op.drop_index(op.f('ix_platform_identity_person_id'), table_name='platform_identity')
    op.drop_table('platform_identity')
    op.drop_table('identity_decision')
    op.drop_index('idx_fe_target', table_name='feedback_event')
    op.drop_table('feedback_event')
    op.drop_index('idx_ee_watcher_observed', table_name='edge_event')
    op.drop_index('idx_ee_target_repo_observed', table_name='edge_event', postgresql_where="target_kind = 'repository'")
    op.drop_index('idx_ee_target_person_observed', table_name='edge_event', postgresql_where="target_kind = 'person'")
    op.drop_index('idx_ee_org_source_observed', table_name='edge_event')
    op.drop_table('edge_event')
    op.drop_index(op.f('ix_convergence_event_target_person_id'), table_name='convergence_event')
    op.drop_index('idx_ce_org_score', table_name='convergence_event')
    op.drop_table('convergence_event')
    op.drop_table('alert_rule')
    op.drop_table('scraper_account')
    op.drop_index(op.f('ix_person_org_id'), table_name='person')
    op.drop_index(op.f('ix_person_entity_type'), table_name='person')
    op.drop_table('person')
    op.drop_table('human_review_queue')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_repository_full_name'), table_name='repository')
    op.drop_table('repository')
    op.drop_table('org')
    # ### end Alembic commands ###
