"""Generate data/twitter_vc_watchlist.txt from the live graph.

Pulls every Person who has a `twitter` PlatformIdentity AND is either:
  - tier='active' for the demo user, OR
  - investor_type='Angel' (regardless of tier)

Per PHASE_2_PLAN.md M8: "every active watcher with a twitter PlatformIdentity,
plus the 76 reference angels with twitter handles. ~100 handles total."

Usage:
    python scripts/build_twitter_watchlist.py
    python scripts/build_twitter_watchlist.py --output data/twitter_vc_watchlist.txt
    python scripts/build_twitter_watchlist.py --include-comments  # add display_name as a comment
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scrapers import cypher  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--user-id", default="demo")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "data" / "twitter_vc_watchlist.txt")
    parser.add_argument("--include-comments", action="store_true",
                        help="Prefix each line with `# {display_name}` for readability.")
    args = parser.parse_args()

    from dotenv import load_dotenv
    from neo4j import GraphDatabase
    load_dotenv(ROOT / ".env")

    driver = GraphDatabase.driver(
        os.environ["NEO4J_URI"],
        auth=(os.environ["NEO4J_USER"], os.environ["NEO4J_PASSWORD"]),
    )

    with driver.session() as session:
        rows = session.run(cypher.QUERY_TWITTER_WATCHERS, user_id=args.user_id).data()
    driver.close()

    if not rows:
        print("WARN: no Persons with twitter handles matched. "
              "Have you run scripts/load_investor_reference.py and "
              "scripts/promote_active_watchlist.py?", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        f.write("# Twitter watchlist — auto-generated by scripts/build_twitter_watchlist.py\n")
        f.write(f"# Source: Persons with twitter PlatformIdentity who are tier='active' OR investor_type='Angel'\n")
        f.write(f"# Total: {len(rows)} handles\n\n")
        for row in rows:
            handle = (row["twitter_handle"] or "").strip()
            if not handle:
                continue
            if args.include_comments:
                f.write(f"# {row['display_name']}\n")
            f.write(handle + "\n")

    print(f"Wrote {len(rows)} handle(s) to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
